### ISSUE TITLE
Error while running after compiling.

### ISSUE THREAD

**Issue by ghost** [Narasimha1997/fake-sms#8] opened 2021-10-11 10:50 UTC
I cloned the repo and built it but when I try to run the compiled file I get the following error. what should I do?
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x77c305]

goroutine 1 [running]:
github.com/anaskhan96/soup.findAllofem.func1(0x0, 0xc00060b0e0, 0x3, 0x3, 0x40cd00)
        /home/narasimha/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:534 +0x445
github.com/anaskhan96/soup.findAllofem(0x0, 0xc00060b0e0, 0x3, 0x3, 0x7b4801, 0xc000489e10, 0xc00047e000, 0x28)
        /home/narasimha/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:538 +0xf2
github.com/anaskhan96/soup.Root.FindAllStrict(0x0, 0x0, 0x0, 0x8a8360, 0xc0002c0200, 0xc00060b0e0, 0x3, 0x3, 0x0, 0x0, ...)
        /home/narasimha/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:313 +0x6c
main.ScrapeAvailableNumbers(0xc000149f48, 0x446c8a, 0xa97e80)
        /home/narasimha/fake-sms/recvsms.go:29 +0x24d
main.main()
        /home/narasimha/fake-sms/main.go:368 +0x26

**Comment by Narasimha1997** [comment] 2021-10-11 13:29
@ParsaBahramin 
Hi, can you say in which step you got this error?

I'm not able to reproduce the error. I cloned the latest updated code and built it.

**Comment by ghost** [comment] 2021-10-11 13:32
> @ParsaBahramin Hi, can you say in which step you got this error?
> 
> I'm not able to reproduce the error. I cloned the latest updated code and built it.

After I built it (and everything was okay) on an Ubuntu Wsl, when I tried to run ./fake-sms in bin/ folder I got this error.

**Comment by Narasimha1997** [comment] 2021-10-16 02:37
When did it crash.? I mean in what step??

**Comment by ghost** [comment] 2021-10-16 09:43
> 
> 
> When did it crash.? I mean in what step??

The moment I ran. The first step after building it.
![Untitled](https://user-images.githubusercontent.com/45267509/137582883-1007b923-de47-4b33-b196-3b5507d91627.png)

**Comment by Narasimha1997** [comment] 2022-01-23 05:26
Closing this issue as we changed the service provider

**Closed as completed by Narasimha1997** 2022-01-23 05:26 UTC
